### ISSUE TITLE
A simple way to double the impact of R-Drop

### ISSUE THREAD

**Issue by guotong1988** [dropreg/R-Drop#10]
Add the TensorFlow code of R-Drop at README.

Thank you very much.

I am afraid that my own coding has some misstake.

**Comment by beyondguo** [comment]
A simple way to double the impact of R-Drop?? Could you please share your method?

**Comment by guotong1988** [comment]
Add the TensorFlow code of R-Drop at README ：）

**Comment by beyondguo** [comment]
兄弟，在哪儿啊？哪里的README？给个链接吧
