### ISSUE TITLE
Readme File for RoBerta example.

### ISSUE THREAD

**Issue by ShreyPandit** [dropreg/R-Drop#11]
Hey @dropreg ,
It would be great if you could make and share a readme file for the RoBerta task, for the pre-processing of dataset, or training of task.

Thanks

**Comment by dropreg** [comment]
> Hey @dropreg ,
> It would be great if you could make and share a readme file for the RoBerta task, for the pre-processing of dataset, or training of task.
> 
> Thanks

Hi, thanks for you attention, you can run roberta code by simly switching the parameter: model_name_or_path, like https://github.com/dropreg/R-Drop/tree/main/huggingface_transformer_src .
