### ISSUE TITLE
pip install --editable .报错

### ISSUE THREAD

**Issue by Shiwen-Ni** [dropreg/R-Drop#15]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/90057377/132990044-c373f51a-9bc2-4f31-8d9c-627fde4c9915.png">

**Comment by Shiwen-Ni** [comment]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/90057377/132990031-49f2a71d-1776-46e6-99b6-61ccf8d7a66f.png">

**Comment by dropreg** [comment]
It is possible that your current account has no permission for install with "develop mode" . May be you can try another command line:  pip install ./
