### ISSUE TITLE
unable to reproduce results on GLUE

### ISSUE THREAD

**Issue by 1024er** [dropreg/R-Drop#16]
**Hi,
    I am trying to  reproduce results on GLUE, but obvious lower than paper.
    I run the code with suggested hyperparameters on 32G V100 - cuda10.2/ubuntu - python 3.6 / pytorch 1.8

**

    _==> run_task_baseline_CoLA.log <==
    [INFO|trainer.py:1963] 2021-10-26 01:37:38,527 >>   Num examples = 1043
    [INFO|trainer.py:1966] 2021-10-26 01:37:38,527 >>   Batch size = 8
    100%|##########| 131/131 [00:05<00:00, 23.67it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 01:37:44,107 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:37:44,107 >>   epoch                     =       9.97
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:37:44,107 >>   eval_loss                 =     1.7947
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:37:44,107 >>   eval_matthews_correlation =     0.6032
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:37:44,107 >>   eval_runtime              = 0:00:05.57
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:37:44,107 >>   eval_samples              =       1043
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:37:44,107 >>   eval_samples_per_second   =    186.945
    
    ==> run_task_baseline_MNLI.log <==
    [INFO|trainer.py:1963] 2021-10-26 08:31:45,749 >>   Num examples = 9832
    [INFO|trainer.py:1966] 2021-10-26 08:31:45,749 >>   Batch size = 8
    100%|##########| 1229/1229 [00:54<00:00, 22.53it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 08:32:40,333 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:32:40,333 >>   epoch                   =      10.09
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:32:40,333 >>   eval_accuracy           =      0.853
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:32:40,333 >>   eval_loss               =     0.8149
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:32:40,333 >>   eval_runtime            = 0:00:54.58
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:32:40,333 >>   eval_samples            =       9832
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:32:40,333 >>   eval_samples_per_second =    180.129
    
    ==> run_task_baseline_MRPC.log <==
    100%|##########| 51/51 [00:02<00:00, 23.40it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 01:30:21,104 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   epoch                   =       9.98
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   eval_accuracy           =      0.848
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   eval_combined_score     =     0.8708
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   eval_f1                 =     0.8935
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   eval_loss               =     1.4835
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   eval_runtime            = 0:00:02.22
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   eval_samples            =        408
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:30:21,104 >>   eval_samples_per_second =    183.422
    
    ==> run_task_baseline_QNLI.log <==
    [INFO|trainer.py:1963] 2021-10-26 03:19:05,420 >>   Num examples = 5463
    [INFO|trainer.py:1966] 2021-10-26 03:19:05,420 >>   Batch size = 8
    100%|##########| 683/683 [00:29<00:00, 22.80it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 03:19:35,416 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 03:19:35,416 >>   epoch                   =      10.11
    [INFO|trainer_pt_utils.py:903] 2021-10-26 03:19:35,416 >>   eval_accuracy           =     0.9143
    [INFO|trainer_pt_utils.py:903] 2021-10-26 03:19:35,416 >>   eval_loss               =     0.5311
    [INFO|trainer_pt_utils.py:903] 2021-10-26 03:19:35,416 >>   eval_runtime            = 0:00:29.99
    [INFO|trainer_pt_utils.py:903] 2021-10-26 03:19:35,416 >>   eval_samples            =       5463
    [INFO|trainer_pt_utils.py:903] 2021-10-26 03:19:35,416 >>   eval_samples_per_second =    182.125
    
    ==> run_task_baseline_QQP.log <==
    100%|##########| 5054/5054 [03:42<00:00, 22.72it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 08:26:18,073 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,073 >>   epoch                   =       9.96
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,073 >>   eval_accuracy           =      0.912
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,073 >>   eval_combined_score     =     0.8972
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,074 >>   eval_f1                 =     0.8824
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,074 >>   eval_loss               =      0.533
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,074 >>   eval_runtime            = 0:03:42.46
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,074 >>   eval_samples            =      40430
    [INFO|trainer_pt_utils.py:903] 2021-10-26 08:26:18,074 >>   eval_samples_per_second =     181.74
    
    ==> run_task_baseline_RTE.log <==
    [INFO|trainer.py:1963] 2021-10-26 01:28:46,682 >>   Num examples = 277
    [INFO|trainer.py:1966] 2021-10-26 01:28:46,682 >>   Batch size = 8
    100%|##########| 35/35 [00:01<00:00, 24.70it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 01:28:48,142 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:28:48,143 >>   epoch                   =       6.53
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:28:48,143 >>   eval_accuracy           =     0.6462
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:28:48,143 >>   eval_loss               =     1.9563
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:28:48,143 >>   eval_runtime            = 0:00:01.46
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:28:48,143 >>   eval_samples            =        277
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:28:48,143 >>   eval_samples_per_second =    189.656
    
    ==> run_task_baseline_SST2.log <==
    [INFO|trainer.py:1963] 2021-10-26 02:33:21,244 >>   Num examples = 872
    [INFO|trainer.py:1966] 2021-10-26 02:33:21,244 >>   Batch size = 8
    100%|##########| 109/109 [00:04<00:00, 23.88it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 02:33:25,854 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 02:33:25,854 >>   epoch                   =       9.95
    [INFO|trainer_pt_utils.py:903] 2021-10-26 02:33:25,854 >>   eval_accuracy           =     0.9255
    [INFO|trainer_pt_utils.py:903] 2021-10-26 02:33:25,854 >>   eval_loss               =     0.6675
    [INFO|trainer_pt_utils.py:903] 2021-10-26 02:33:25,854 >>   eval_runtime            = 0:00:04.60
    [INFO|trainer_pt_utils.py:903] 2021-10-26 02:33:25,854 >>   eval_samples            =        872
    [INFO|trainer_pt_utils.py:903] 2021-10-26 02:33:25,854 >>   eval_samples_per_second =    189.197
    
    ==> run_task_baseline_STSB.log <==
    100%|##########| 188/188 [00:08<00:00, 22.73it/s]
    [INFO|trainer_pt_utils.py:898] 2021-10-26 01:34:24,178 >> ***** eval metrics *****
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   epoch                   =       9.99
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   eval_combined_score     =     0.8904
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   eval_loss               =     0.9493
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   eval_pearson            =     0.8921
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   eval_runtime            = 0:00:08.31
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   eval_samples            =       1500
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   eval_samples_per_second =    180.347
    [INFO|trainer_pt_utils.py:903] 2021-10-26 01:34:24,178 >>   eval_spearmanr          =     0.8887_

**Comment by dropreg** [comment]
Hi, @1024er please refer to #6

**Comment by apeterswu** [comment]
Close the comment to refer to another issue.
