### ISSUE TITLE
Where is R-Drop code in R-Drop/huggingface_transformer_src/bert_rdrop/run_glue.py?

### ISSUE THREAD

**Issue by zhenshiqi1996** [dropreg/R-Drop#18]

**Comment by TxiHu** [comment]
Can you find the code for the two dropouts?

**Comment by ruoyusong** [comment]
i also have this question

**Comment by TxiHu** [comment]
> i also have this question

我觉得两次dropout其实就是把同一个输入输入到模型两次。两次会产生一些微小差别。

**Comment by ruoyusong** [comment]
那KL散度呢 源码里没找到哎

**Comment by ruoyusong** [comment]
> > i also have this question
> 
> 我觉得两次dropout其实就是把同一个输入输入到模型两次。两次会产生一些微小差别。

那KL散度呢 源码里没找打哎

**Comment by TxiHu** [comment]
它文章里的Usage里已经说了咋用。  写了损失计算公式

**Comment by TxiHu** [comment]
> > > i also have this question
> > 
> > 
> > 我觉得两次dropout其实就是把同一个输入输入到模型两次。两次会产生一些微小差别。
> 
> 那KL散度呢 源码里没找打哎

它文章里的Usage里已经写了损失计算公式呀。

**Comment by XiaoqingNLP** [comment]
写在了modeling_bert.py 里面bert_kl 函数就是
