### ISSUE TITLE
How to use the data parallel in r-drop. 

### ISSUE THREAD

**Issue by xinxinxing** [dropreg/R-Drop#32]
how to use the data parallel in r-drop. 
As I use the distributed-world-size ,the bleu is lower than the one gpu.
Here is my train.sh
![image](https://user-images.githubusercontent.com/48848900/192675802-f46f3fb6-6b98-4cfb-8ef4-f9b5ecd6b646.png)

**Comment by apeterswu** [comment]
Hi @xinxinxing , the default parallel mode in fairseq is the data parallel. So if you are running on a single node with 4 GPU cards, you don't need to specify the distributed-word-size, just remove this arg and run in a normal way.
