### ISSUE TITLE
Fairseq tasks install work?

### ISSUE THREAD

**Issue by kungfu-eric** [dropreg/R-Drop#4]
I followed the instructions entering:
`cd R-Drop/fairseq_src/`
`pip install --editable .`

I still get:

> fairseq-train: error: argument --task: invalid choice: 'rdrop_translation' (choose from 'translation', 'multilingual_translation', 'semisupervised_translation', 'language_modeling', 'speech_to_text', 'masked_lm', 'translation_from_pretrained_xlm', 'audio_pretraining', 'denoising', 'multilingual_denoising', 'legacy_masked_lm', 'translation_lev', 'sentence_prediction', 'sentence_ranking', 'cross_lingual_lm', 'translation_from_pretrained_bart', 'multilingual_masked_lm', 'translation_multi_simple_epoch', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')

It's not finding the task. I'm running 
`bash script/run_train.sh` 
in the examples/summeration_rdrop/ folder.

**Comment by dropreg** [comment]
It is necessary to add script parameter (--user-dir)  for fairseq customized task, and we have fixed this problem.  Thanks for your question !
