### ISSUE TITLE
Summarization task fails with 'Trying to backward through the graph a second time'

### ISSUE THREAD

**Issue by paul-chelarescu** [dropreg/R-Drop#8]
Hi, by following the instructions verbatim in the readme file, the summarization task defined [here ](https://github.com/dropreg/R-Drop/blob/main/fairseq_src/examples/summeration_rdrop/script/run_train.sh) will fail with the following error

`RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.
`, 
if the following four lines are not removed from [here](https://github.com/dropreg/R-Drop/blob/main/fairseq_src/examples/summeration_rdrop/summeration_rdrop_src/rdrop_translation.py#L23)

```        
        if ignore_grad:
            loss *= 0
        with torch.autograd.profiler.record_function("backward"):
            optimizer.backward(loss)             
```

It seems like these lines are duplicated in [this](https://github.com/dropreg/R-Drop/blob/f40bcae81b9d807e15d41986c406c440a211750f/fairseq_src/examples/summeration_rdrop/summeration_rdrop_src/loss/rdrop_cross_entropy_loss.py#L153) part of the code, causing the error.

**Comment by ShreyPandit** [comment]
Hey, Facing the same Issue...
@dropreg can you have a look at it... Thanks!

**Comment by dropreg** [comment]
Sorry for late reply, we have fix this bug.
